
function hw_2_4_3(A, varargin)
fig = figure;
subplot(2, 1, 1);
[U, S, V] = svd(A);
S = diag(S);
t = linspace(0, 2*pi);
% ---------------------

plot(cos(t), sin(t), '--k');
hold on
x1 = linspace(0, V(1, 1));
y1 = linspace(0, V(1, 2));
x2 = linspace(0, V(2, 1));
y2 = linspace(0, V(2, 2));
plot(x1, y1, 'r');
plot(x2, y2, 'b');
legend('V_1', 'V_2');
titlestr = strcat('right sing. vects in unit circle for', ...
    sprintf('A = [%03.f %03.f; %03.f %03.f]', A(1,1), A(1, 2), A(2, 1), A(2, 2)));
title(titlestr);
axis([-1, 1, -1, 1])

% ------------------

subplot(2, 1, 2);
plot(S(1)*cos(t), S(2)*sin(t), '--')
hold on
x1 = linspace(0, S(1)*U(1, 1));
y1 = linspace(0, S(2)*U(1, 2));
x2 = linspace(0, S(1)*U(2, 1));
y2 = linspace(0, S(2)*U(2, 2));
plot(x1, y1, 'r')
plot(x2, y2, 'b')
legend('\sigma_1U_1', '\sigma_2U_2');
axis_bounds = max([max(x1), max(x2), max(y1), max(y2)]);
axis_bounds = max(axis_bounds, 3)
titlestr = strcat('left sing. vects in ellipse generated by', ...
    sprintf('A = [%03.f %03.f; %03.f %03.f]', A(1,1), A(1, 2), A(2, 1), A(2, 2)));
title(titlestr);
axis([-axis_bounds, axis_bounds, -axis_bounds, axis_bounds]);

if nargin > 1
    filename = varargin{1};
    try saveas(fig, filename)
    catch
        warning('invalid filename!')
    end
end
end

